name: Preprocess Student Data

on:
  push:
    paths:
      - "data/StudentsPerformance.csv"
      - "automate_Nama-siswa.py"
  workflow_dispatch:

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install Pandas
      run: pip install pandas

    - name: Run Preprocessing Script
      run: |
        python -c "
import automate_Nama_siswa as auto
df = auto.preprocess_student_data('data/StudentsPerformance.csv')
df.to_csv('processed/processed_data.csv', index=False)
"
        
    - name: Commit processed data
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add processed/processed_data.csv
        git commit -m 'Update processed data'
        git push
